### ISSUE TITLE
Program hangs when sync complete

### ISSUE THREAD

**Issue by DeclanGS** [Zingabopp/BeatSync#30]
hi! thanks for all the amazing work.

i've used beatsync several times over the past few weeks with no trouble at all. however today when i ran it to download some new songs it got stuck. it finished downloading several songs, but then just sat there; the line describing the last download wasn't followed by anything at all. When I rerun beatsync now, it just hangs on " Starting BeastSaberBookmarks feed..."

The _logs_ indicate that beatsync is reading the feed properly and "receiving no new songs, last page reached" (which is correct). but it seems like something isn't exiting cleanly so the actual program never reports that it's finished. re-downloading the program didn't help. Not sure what changed between last week when it worked fine, and now. :(

obviously not a showstopper, program still works. but i thought you'd want to know. thanks again!

**Comment by Zingabopp** [comment]
Can you post the log from when this happened?

**Comment by DeclanGS** [comment]
Hi! Happy to— and, sorry, it turned out I was wrong about two things. When I went back to look at the logs, I found out that a. there WERE actually still some songs left to fetch that the app hadn't successfully fetched at first, and b. it didn't just hang forever. It hung for as long as I watched it (maybe ten minutes), but sometime later (maybe much later) it finally timed out and continued with an error message as shown.

```[BeatSyncConsole - Info]: Starting BeatSyncConsole v0.9.1.0 | Official-master-b957a15
[BeatSyncConsole - Info]: Running the latest release of BeatSyncConsole.
[BeatSyncConsole - Info]: %ASSEMBLYDIR%\configs\BeatSyncConsole.json not found, creating a new one.
[BeatSyncConsole - Info]: %ASSEMBLYDIR%\configs\BeatSync.json not found, creating a new one.
[BeatSyncConsole - Info]:   Steam: D:\SteamLibrary\steamapps\common\Beat Saber
[BeatSyncConsole - Info]: Found 1 game install, enabling for BeatSyncConsole: Steam: D:\SteamLibrary\steamapps\common\Beat Saber
[BeatSyncConsole - Info]: Using the following targets:
[BeatSyncConsole - Info]:   GameInstall: D:\SteamLibrary\steamapps\common\Beat Saber
[BeatSyncConsole - Info]: Hashing songs in 'D:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels'...
[BeatSyncLib - Debug]: Finished hashing in 51ms.
[BeatSyncConsole - Info]: Hashed 112 songs in D:\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels in 0sec.
[BeatSyncLib - Warn]:   No FavoriteMappers found, skipping...
[BeatSyncLib - Info]:   Finished BeatSaver reading: (0/0).
[BeatSyncLib - Info]:   Starting BeastSaberBookmarks feed...
[SongFeedReader - Debug]: Getting songs from 'https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=1&count=50'
[SongFeedReader - Debug]: Getting songs from 'https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=2&count=50'
[SongFeedReader - Debug]: Getting songs from 'https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=3&count=50'
[SongFeedReader - Debug]: Getting songs from 'https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=4&count=50'
[SongFeedReader - Debug]: Getting songs from 'https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=5&count=50'
[SongFeedReader - Debug]: Receiving 50 potential songs from https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=1&count=50
[SongFeedReader - Debug]: Receiving 50 potential songs from https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=2&count=50
[SongFeedReader - Debug]: Receiving 8 potential songs from https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=Skaramuche&page=3&count=50
[SongFeedReader - Debug]: Received no new songs, last page reached.
[BeatSyncLib - Warn]: Error in DownloadJob.RunAsync: The response ended prematurely, with at least 2567652 additional bytes expected.
[BeatSyncLib - Debug]:    at BeatSyncLib.Downloader.Downloading.DownloadJob.RunAsync(CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Downloader/Downloading/DownloadJob.cs:line 146
[BeatSyncConsole - Info]:       Job failed: (C4EE) Neil Cicierega - Wallspin by Ryger
[BeatSyncLib - Warn]: Error in DownloadJob.RunAsync: The response ended prematurely, with at least 402767 additional bytes expected.
[BeatSyncLib - Debug]:    at BeatSyncLib.Downloader.Downloading.DownloadJob.RunAsync(CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Downloader/Downloading/DownloadJob.cs:line 146
[BeatSyncConsole - Info]:       Job failed: (6F13) Block Rockin' Beats - The Chemical Brothers by Ryger
[BeatSyncConsole - Info]:       Job completed successfully: (4308) One Week - Barenaked Ladies by Ryger
[BeatSyncConsole - Info]:       Job completed successfully: (6AB0) Spooky Scary Skeletons (Andrew Gold Remix) by Ryger
[BeatSyncConsole - Info]:       Job completed successfully: (147E) Skyrim Theme - Song of the Dragonborn by whattheshark
[BeatSyncConsole - Info]:       Job completed successfully: (9D0) Fake Love by BTS (Benny Original™) by bennydabeast
[BeatSyncConsole - Info]:       Job completed successfully: (FB) Kids by MGMT (BennyDaBeast) by bennydabeast
[BeatSyncLib - Warn]: Error in DownloadJob.RunAsync: The response ended prematurely, with at least 2368928 additional bytes expected.
[BeatSyncLib - Debug]:    at BeatSyncLib.Downloader.Downloading.DownloadJob.RunAsync(CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Downloader/Downloading/DownloadJob.cs:line 146
[BeatSyncLib - Debug]: Found existing playlist for BeatSyncRecent with 89 songs.
[BeatSyncLib - Debug]: Found existing playlist for BeastSaberBookmarks with 92 songs.
[BeatSyncLib - Info]:   Finished BeastSaberBookmarks feed: (105/108, 100 skipped).
[BeatSyncLib - Info]:   Finished BeastSaber reading: (105/108, 100 skipped).
[BeatSyncLib - Debug]: Found existing playlist for BeatSyncRecent with 94 songs.
[BeatSyncConsole - Info]: Finished after 1564.7252475s: 105/108, 100 skipped
Stopping LogManager.

**Comment by Zingabopp** [comment]
I'll have to make sure the download timeouts are working correctly. At least this shows my handling of partial downloads worked correctly :)
