### ISSUE TITLE
The app no longer works

### ISSUE THREAD

**Issue by koman709** [Zingabopp/BeatSync#49]
A couple of days the maps are not downloaded, and the following error appears in the console.

`[Error @ 2022-01-22 14:07:36 | BeatSyncConsole]: Fatal Error in BeatSyncConsole: URL 'https://api.beatsaver.com/maps/latest?automapper=false&before=2022-01-09T11:33:11.094Z' was previously read, aborting to avoid possible infinite loop.
   at SongFeedReaders.Readers.DatedFeedAsyncEnumerator.MoveNextAsync(CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/Libs/BeatSaberDataProvider/SongFeedReaders/Readers/DatedFeedAsyncEnumerator.cs:line 93
   at SongFeedReaders.Readers.BeatSaver.BeatSaverReader.GetSongsFromFeedAsync(IFeedSettings _settings, IProgress``1 progress, CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/Libs/BeatSaberDataProvider/SongFeedReaders/Readers/BeatSaver/BeatSaverReader.cs:line 257
   at BeatSyncLib.Downloader.SongDownloader.GetBeatSaverAsync(BeatSyncConfig config, IJobBuilder jobBuilder, JobManager jobManager, CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Downloader/SongDownloader.cs:line 176
   at BeatSyncLib.Downloader.SongDownloader.RunAsync(BeatSyncConfig config, IJobBuilder jobBuilder, JobManager manager, CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Downloader/SongDownloader.cs:line 34
   at BeatSyncConsole.Program.Main(String[] args) in /_/BeatSyncConsole/Program.cs:line 306`

**Comment by GigaFyde** [comment]
A bit late maybe, but the app works fine for me @koman709
