### ISSUE TITLE
Fatal Error in BeatSyncConsole: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by Bluscream** [Zingabopp/BeatSync#9]
```
[BeatSyncConsole - Info]: Starting BeatSyncConsole v0.5.1.0
[BeatSyncConsole - Info]: Using BeatSync config 'configs\BeatSync.json'.
[BeatSyncConsole - Info]: Using the following targets:
[BeatSyncConsole - Info]:   GameInstall: G:\Steam\steamapps\common\Beat Saber
[BeatSyncConsole - Info]: Hashed 174 songs in G:\Steam\steamapps\common\Beat Saber\Beat Saber_data\CustomLevels.
[BeatSyncConsole - Info]:   Starting BeatSaverDownloads feed...
[BeatSyncConsole - Info]:   Starting BeastSaberBookmarks feed...
[BeatSyncConsole - Info]:       Job completed successfully: (217) Beat it - Michael Jackson by freeek
[BeatSyncConsole - Info]:       Job completed successfully: (141) GANGNAM STYLE by greatyazer
[BeatSyncConsole - Info]:       Job completed successfully: (32E) Daft Punk - Harder Better Faster Stronger by runrockgame
[BeatSyncConsole - Info]:   Finished BeatSaverDownloads feed: (5/5, 1 skipped).
[BeatSyncConsole - Warn]:   No FavoriteMappers found, skipping...
[BeatSyncConsole - Info]:   Finished BeatSaver reading: (5/5, 1 skipped).
Press Enter to continue...
[BeatSyncConsole - Error]: Fatal Error in BeatSyncConsole: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at BeatSyncConsole.Program.GetBeastSaberAsync(BeatSyncConfig config, IJobBuilder jobBuilder, JobManager jobManager) in .\Program.cs:line 171
   at BeatSyncConsole.Program.Main(String[] args) in .\Program.cs:line 438

```

**Comment by Zingabopp** [comment]
Does this happen repeatedly, or was it a one-time thing?

**Comment by Bluscream** [comment]
that's weird because i definitly have a username set

```
  "BeastSaber": {
    "Enabled": true,
    "Username": "Bluscream",
```

**Comment by Zingabopp** [comment]
Give this build a try, should give some better information. There's definitely something going wrong with the BeastSaberReader, not sure what though.

https://github.com/Zingabopp/BeatSync/suites/771838850/artifacts/8060717

**Comment by Bluscream** [comment]
that fixed it 👍
